# -*- coding: utf-8 -*-
"""py02-lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbsSBdgSEqU1j25s4NCKWDhv2ivpuRZd
"""

coffee = input("커피 이름을 입력하세요: ")
price = int(input("가격을 입력하세요: "))
quantity = int(input("수량을 입력하세요: "))

total = price * quantity

print("====== 영수증 ======")
print("커피 이름:", coffee)
print("가격:", price)
print("수량:", quantity)
print("-------------------")
print("총 금액:", total)
print("===================")